# Generated by Django 4.1.4 on 2022-12-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.BigAutoField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipoDeTransaccion', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.BigIntegerField(max_length=100)),
            ],
        ),
    ]
