# Generated by Django 4.1.4 on 2022-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='id_factura',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(),
        ),
    ]
