# Generated by Django 4.1.4 on 2022-12-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_detallefactura_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
