# Generated by Django 4.1.4 on 2022-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_detallefactura_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
