# Generated by Django 4.1.4 on 2022-12-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_destallefactura', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=65)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=65)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.facturacion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
