# Generated by Django 4.1.4 on 2022-12-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_facturacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
    ]
